"""
Configuration constants for the curated bus-stop integration pipeline.
"""

from pathlib import Path

# Resolve the project root from this pipeline file location.
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Required input files.
MISSING_UNIQUE_STOPS_CSV = PROJECT_ROOT / "data" / "processed" / "bus_stop_missing" / "missing_bus_unique_stops.csv"
OD_CURATED_CSV = PROJECT_ROOT / "data" / "curated" / "od_curated_20251111.csv"
NODE_INFO_CSV = PROJECT_ROOT / "data" / "reference" / "노드정보.csv"

# Output directories.
OUTPUT_MISSING_DIR = PROJECT_ROOT / "data" / "processed" / "bus_stop_missing"
OUTPUT_LOCATION_DIR = PROJECT_ROOT / "data" / "processed" / "bus_stop_location"

# Output files generated by the integration pipeline.
CURATED_REFERENCE_CSV = OUTPUT_LOCATION_DIR / "curated_bus_stop_reference.csv"
SERVICE_MAPPING_CSV = OUTPUT_LOCATION_DIR / "bus_stop_demand_node_mapping.csv"
ARS_MAPPING_CSV = OUTPUT_LOCATION_DIR / "bus_stop_ars_node_mapping.csv"
INTEGRATED_LOCATION_PATCH_CSV = OUTPUT_LOCATION_DIR / "integrated_bus_stop_location_patch.csv"
UNRESOLVED_CSV = OUTPUT_LOCATION_DIR / "bus_stop_mapping_unresolved.csv"
AMBIGUOUS_CSV = OUTPUT_LOCATION_DIR / "bus_stop_mapping_ambiguous.csv"
SUMMARY_CSV = OUTPUT_LOCATION_DIR / "curated_mapping_summary.csv"

# Source delimiter and source column names for od_curated_YYYYMMDD.csv. 
OD_SEP = "|"
OD_COLUMNS = {
    "date": "기준일자",
    "route_name": "노선명",
    "converted_route_id": "전환_노선ID",
    "passengers": "승객수",
    "boarding_seq": "승차_정류장순번",
    "boarding_ars": "승차_정류장ARS",
    "boarding_standard_node_id": "승차_정류장표준코드",
    "boarding_stop_name": "승차_정류장명",
    "alighting_seq": "하차_정류장순번",
    "alighting_ars": "하차_정류장ARS",
    "alighting_standard_node_id": "하차_정류장표준코드",
    "alighting_stop_name": "하차_정류장명",
}

# Source column names for node_info.csv.
NODE_INFO_COLUMNS = {
    "canonical_node_id": "노드ID",
    "stop_name": "노드명",
    "lng": "좌표X",
    "lat": "좌표Y",
    "region_id": "지역ID",
    "ars_id": "정류장번호",
    "use_yn": "사용여부",
    "standard_code_yn": "표준코드여부(1:표준/0:비표준)",
}

# Coordinate sanity bounds for South Korea and the nearby service area.
LAT_MIN = 33.0
LAT_MAX = 39.5
LNG_MIN = 124.0
LNG_MAX = 132.5
