CREATE TABLE IF NOT EXISTS bus_stop_demand_node_mapping (
    service_id VARCHAR(100),
    service_id_type VARCHAR(50),
    route_name VARCHAR(200),
    converted_route_id VARCHAR(100),
    demand_node_id VARCHAR(20),
    canonical_node_id VARCHAR(100),
    ars_id VARCHAR(20),
    stop_name VARCHAR(200),
    node_info_stop_name VARCHAR(200),
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    region_id VARCHAR(50),
    seq INTEGER,
    side VARCHAR(20),
    match_method VARCHAR(100),
    match_confidence DOUBLE PRECISION,
    reference_rows INTEGER,
    passenger_sum BIGINT,
    canonical_candidate_count INTEGER
);