-- 01_curated_od.sql
-- Curated OD table and holiday reference.
--
-- IMPORTANT:
-- analysis_table_final is the ONLY table mapped by a JPA @Entity
-- (com.ian.transit.curatedod.infrastructure.CuratedOdRecord).
-- Because application.yaml uses `ddl-auto: validate`, the API server will
-- FAIL TO START if this table or any of its columns is missing.
-- Every other table is accessed through JdbcTemplate and therefore fails
-- only at request time, not at boot.
--
-- Column names and types are derived from CuratedOdRecord.java.
-- Do not rename columns without changing the entity.
--
-- The numeric columns are numeric on purpose. The original SQL Server table
-- declared every column as VARCHAR; they were later converted because the
-- implicit CASTs were disabling indexes:
--
--   ALTER TABLE Analysis_Table_Final ALTER COLUMN 승차_정류장순번 INT;
--   ALTER TABLE Analysis_Table_Final ALTER COLUMN 하차_정류장순번 INT;
--   ALTER TABLE Analysis_Table_Final ALTER COLUMN 승객수 INT;
--   ALTER TABLE Analysis_Table_Final ALTER COLUMN 전환_노선ID BIGINT;
--
-- Reverting these to text would reintroduce that regression and would also
-- fail Hibernate validation, since the entity maps Integer and Long.
--
-- Verified against the live database: the four numeric columns are bigint and
-- integer as declared here. The VARCHAR lengths are 255 because the table was
-- originally generated by Hibernate, whose default length for an unannotated
-- String field is 255. They are reproduced as-is so a fresh database matches
-- the working one; narrowing them is a separate, deliberate migration.
--
-- anomaly_data mirrors this column list exactly; it is the quarantine target
-- for rows removed by the correction pipeline.

-- NO PRIMARY KEY IS DEFINED HERE. This is deliberate.
--
-- The JPA entity declares a composite @IdClass of
-- (기준일자, 노선명, 승차_정류장ars, 하차_정류장ars), but that combination is NOT
-- unique in the actual data. OdCorrectionCommandRepository ranks rows with
-- ROW_NUMBER() OVER (PARTITION BY 노선명, 승차_정류장ars) over differing
-- 승차_정류장순번 values, which only makes sense when duplicates exist.
--
-- A database-level primary key on those columns would therefore:
--   1. reject the curated OD load, and
--   2. break the correction pipeline, which UPDATEs 승차_정류장ars and
--      하차_정류장ars in place and would collide mid-statement.
--
-- Hibernate `validate` checks tables and columns only, not keys or
-- constraints, so omitting the key costs nothing at startup.

CREATE TABLE IF NOT EXISTS public.analysis_table_final (
    기준일자                VARCHAR(255),
    노선명                  VARCHAR(255),
    전환_노선id             BIGINT,
    승차_정류장순번          INTEGER,
    승차_정류장ars          VARCHAR(255),
    승차_정류장표준코드       VARCHAR(255),
    승차_정류장명            VARCHAR(255),
    하차_정류장순번          INTEGER,
    하차_정류장ars          VARCHAR(255),
    하차_정류장표준코드       VARCHAR(255),
    하차_정류장명            VARCHAR(255),
    승객수                  INTEGER
);

-- Lookup index for date + route filtering used by congestion and OD APIs.
CREATE INDEX IF NOT EXISTS idx_analysis_table_final_date_route
ON public.analysis_table_final (기준일자, 노선명);

-- Boarding-stop sequence lookup used by the OD correction pipeline.
CREATE INDEX IF NOT EXISTS idx_analysis_table_final_route_seq
ON public.analysis_table_final (노선명, 승차_정류장순번);

-- Quarantine table for rows removed during OD correction.
-- Column order must match analysis_table_final because the pipeline uses
-- INSERT INTO anomaly_data SELECT a.* ... with no explicit column list.
CREATE TABLE IF NOT EXISTS public.anomaly_data (
    기준일자                VARCHAR(255),
    노선명                  VARCHAR(255),
    전환_노선id             BIGINT,
    승차_정류장순번          INTEGER,
    승차_정류장ars          VARCHAR(255),
    승차_정류장표준코드       VARCHAR(255),
    승차_정류장명            VARCHAR(255),
    하차_정류장순번          INTEGER,
    하차_정류장ars          VARCHAR(255),
    하차_정류장표준코드       VARCHAR(255),
    하차_정류장명            VARCHAR(255),
    승객수                  INTEGER
);

-- Holiday reference used by PredictionFeatureService and model training.
--
-- Verified against the live database.
--
-- 날짜 must be DATE, not text: PredictionFeatureService binds a java.time
-- LocalDate directly, and train_xgboost_dayofweek.py reads it through
-- pd.to_datetime(). A VARCHAR column would silently break holiday detection,
-- making every day look like a non-holiday.
--
-- The second column is holiday_name, in English. The predecessor project's
-- loader used a Korean column name; it was renamed during the migration to
-- this repository, so the old loader is not a reliable source here.
--
CREATE TABLE IF NOT EXISTS public.holiday_config (
    날짜          DATE PRIMARY KEY,
    holiday_name  VARCHAR(100)
);
